<#
.SYNOPSIS
    Khởi tạo CodeGraph index cho một project cụ thể
    
.DESCRIPTION
    Chạy 'codegraph init -i' trong thư mục project được chỉ định.
    Tạo file .codegraph/ chứa SQLite database lưu call graph, dependency tree
    của toàn bộ codebase để AI Agent có thể query mà không cần đọc file thô.
    
.PARAMETER ProjectPath
    Đường dẫn đến project cần index. Mặc định là thư mục hiện tại.
    
.PARAMETER AddToGitignore
    Tự động thêm .codegraph/ vào .gitignore (mặc định: true)
    
.EXAMPLE
    # Index project hiện tại
    .\init-codegraph.ps1
    
    # Index project khác
    .\init-codegraph.ps1 -ProjectPath "C:\Projects\MyApp"
    
    # Index mà không sửa .gitignore
    .\init-codegraph.ps1 -AddToGitignore:$false

.NOTES
    Antigravity-Skill-VNese — MK11 Code Search Tools
    Chạy script install-codesearch-tools.ps1 trước nếu chưa cài CodeGraph.
#>

param(
    [string]$ProjectPath = ".",
    [bool]$AddToGitignore = $true
)

function Write-Header($msg) { Write-Host "`n══════════════════════════════════════" -ForegroundColor Cyan
                               Write-Host "  $msg" -ForegroundColor Cyan
                               Write-Host "══════════════════════════════════════`n" -ForegroundColor Cyan }
function Write-Step($msg)    { Write-Host "🔄 $msg" -ForegroundColor Blue }
function Write-Success($msg) { Write-Host "✅ $msg" -ForegroundColor Green }
function Write-Warn($msg)    { Write-Host "⚠️  $msg" -ForegroundColor Yellow }
function Write-Fail($msg)    { Write-Host "❌ $msg" -ForegroundColor Red }

Write-Header "📊 CodeGraph — Project Indexer"

# Resolve project path
$resolvedPath = Resolve-Path $ProjectPath -ErrorAction SilentlyContinue
if (-not $resolvedPath) {
    Write-Fail "Không tìm thấy thư mục: $ProjectPath"
    exit 1
}
$projectDir = $resolvedPath.Path
Write-Host "📂 Project: $projectDir" -ForegroundColor White

# Check codegraph installed
Write-Step "Kiểm tra codegraph..."
$cgCheck = Get-Command codegraph -ErrorAction SilentlyContinue
if (-not $cgCheck) {
    Write-Fail "codegraph chưa được cài đặt!"
    Write-Warn "Chạy trước: .\scripts\install-codesearch-tools.ps1"
    exit 1
}
Write-Success "codegraph đã sẵn sàng"

# Change to project directory and init
Write-Step "Khởi tạo CodeGraph index..."
Push-Location $projectDir

try {
    codegraph init -i
    if ($LASTEXITCODE -eq 0) {
        Write-Success "Index đã tạo xong trong: $projectDir\.codegraph\"
    } else {
        Write-Fail "codegraph init thất bại (exit code: $LASTEXITCODE)"
        Pop-Location
        exit 1
    }
} catch {
    Write-Fail "Lỗi: $_"
    Pop-Location
    exit 1
}

# Add to .gitignore
if ($AddToGitignore) {
    $gitignorePath = Join-Path $projectDir ".gitignore"
    $entry = ".codegraph/"
    
    if (Test-Path $gitignorePath) {
        $content = Get-Content $gitignorePath -Raw
        if ($content -notmatch [regex]::Escape($entry)) {
            Write-Step "Thêm .codegraph/ vào .gitignore..."
            Add-Content -Path $gitignorePath -Value "`n# CodeGraph index (generated by Antigravity)`n$entry"
            Write-Success ".gitignore đã cập nhật"
        } else {
            Write-Warn ".codegraph/ đã có trong .gitignore, bỏ qua"
        }
    } else {
        Write-Step "Tạo .gitignore mới..."
        Set-Content -Path $gitignorePath -Value "# CodeGraph index (generated by Antigravity)`n$entry"
        Write-Success ".gitignore đã tạo"
    }
}

# Verify status
Write-Step "Kiểm tra trạng thái index..."
$status = codegraph status 2>&1
Write-Host $status -ForegroundColor Gray

Pop-Location

Write-Header "✅ Hoàn thành"
Write-Host "CodeGraph đã index project thành công!" -ForegroundColor Green
Write-Host ""
Write-Host "📖 Các lệnh hữu ích:" -ForegroundColor Cyan
Write-Host "  codegraph status                       # Xem trạng thái index" -ForegroundColor Gray
Write-Host "  codegraph callers --symbol <TênHàm>   # Ai gọi hàm này?" -ForegroundColor Gray
Write-Host "  codegraph impact  --symbol <TênHàm>   # BLAST RADIUS analysis" -ForegroundColor Gray
Write-Host "  codegraph deps    --file <path>        # Dependency tree của file" -ForegroundColor Gray
Write-Host ""
Write-Host "📚 Xem thêm: skills\mk11\codegraph-semble\SKILL.md" -ForegroundColor Cyan
